# databases:
# - name: securekey
#   plan: free
#   databaseName: securekey
#   user: securekey

# services:
# - type: web
#   name: securekey
#   runtime: python
#   plan: free
#   buildCommand: "pip install -r requirements.txt"
#   startCommand: "gunicorn securekey.wsgi:application"
#   envVars:
#   -key:DATABASE_URL
#    fromDatabase:
#      name: securekey
#      property:connectionString
#   -key:SECRET_KEY
#    generatedValue: true
#   -key: DEBUG
#    value: "False"
#   -key:REDIS_URL
#    sync:false
#   -key:RABBITMQ_URL
#    sync:false

   
databases:
  - name: securekey
    plan: free
    databaseName: securekey
    user: securekey

services:
  - type: web
    name: securekey
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn securekey.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: securekey
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false