# Generated by Django 5.0.6 on 2026-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_product_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
