# Generated by Django 6.1 on 2026-08-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_private_key_vendor_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LICENSE_GENERATED', 'License Generated'), ('LICENSE_REVOKED', 'License Revoked'), ('LICENSE_VALIDATION', 'License Validation')], max_length=30)),
                ('license_key', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('INVALID', 'Invalid'), ('NOT_FOUND', 'Not Found'), ('SUCCESS', 'Success')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
