# Generated by Django 6.1 on 2026-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_validationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
