# Generated by Django 6.1 on 2026-08-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_validationlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationlog',
            name='license_key',
            field=models.CharField(max_length=1024),
        ),
    ]
